const stars = [
    {   "id": "0",
        "name":"Thai Nguyen",
        "hometown": "Los Angeles",
        "favorite_foods":["sushi","tacos","pastrami sandwitch","house salad"],
        "favorite_musics": ["variety"],
        "favorite_vacation_locations": ["Tokyo, Japan"],
        "hobbies": ["coding", "running"],
        "superhero_powers": ["invisible", "strength"]
    },
    {   "id": "1",
        "name":"Brock Falfas",
        "hometown": "Florida",
        "favorite_foods":[],
        "favorite_musics": [],
        "favorite_vacation_locations": [],
        "hobbies": [],
        "superhero_powers": []
    },
    {   "id": "2",
        "name":"Eli Sacks",
        "hometown": "Toledo",
        "favorite_foods":["Stir-Fry", "Chicken", "Sushi"],
        "favorite_musics": ["Ska", "Pop crap"],
        "favorite_vacation_locations": ["Tokyo", "Vancouver"],
        "hobbies": ["Tabletop RPG", "Video Games"],
        "superhero_powers": ["none", "suckitude"]
    },
    {   "id": "2",
        "name":"Bishop Lake",
        "hometown": "",
        "favorite_foods":[],
        "favorite_musics": [],
        "favorite_vacation_locations": [],
        "hobbies": [],
        "superhero_powers": []
    },
    {   "id": "4",
        "name":"Andrew Allen",
        "hometown": "",
        "favorite_foods":[],
        "favorite_musics": [],
        "favorite_vacation_locations": [],
        "hobbies": [],
        "superhero_powers": []
    },
    {   "id": "5",
        "name":"Sheila Eichenberger",
        "hometown": "Oregon",
        "favorite_foods":[],
        "favorite_musics": [],
        "favorite_vacation_locations": [],
        "hobbies": [],
        "superhero_powers": []
    },
    {   "id": "6",
        "name":"Avni Patel Thompson",
        "hometown": "Vancouver, Canada",
        "favorite_foods":[],
        "favorite_musics": [],
        "favorite_vacation_locations": [],
        "hobbies": [],
        "superhero_powers": []
    },
    {   "id": "7",
        "name":"Armando Roman",
        "hometown": "CA",
        "favorite_foods":[],
        "favorite_musics": [],
        "favorite_vacation_locations": [],
        "hobbies": [],
        "superhero_powers": []
    },
    {   "id": "8",
        "name":"Suparada Saitalae",
        "hometown": "",
        "favorite_foods":[],
        "favorite_musics": [],
        "favorite_vacation_locations": [],
        "hobbies": [],
        "superhero_powers": []
    }
]

export default stars;